### PR TITLE
improving compression by 8x

### PR DESCRIPTION
**Pull request by 5731la**
you chose a compression algorithm that is 8 times slower that gives you a disk gain by 10.5% which is NOT worth it for doing bulk addrs!!!!!

### CODE REVIEW

**Comment by 007** [comment]
I would argue the opposite - you should add every possible option to compress as much as possible.

You're talking about 50MB of data - it's not going to break the bank or CPU to compress the hell out of it.

**Comment by 5731la** [comment]
If you want to run multiple instances of this, you need the CPU power and, right now, this is the best way. Think about it, you gain .2 MB (approx on a 2M file as in readme) but can run 1/8 the threads. Storage usually isn't very expensive so IMO it's worth it.

**Comment by mrcbax** [comment]
With the current survey results I have to process 10TB of compressed data. Which means I have to download it all first. I Need it as small as I can get it at the cost of some CPU cycles.

**Comment by mrcbax** [comment]
If it gets it smaller great. I just don't want to kill people's cpus too. Its a balance. I chose XZ_OPT=9 because it is what I am familiar with.

**Comment by 5731la** [comment]
To be clear, this is without the final compression which can be as strong
as it needs. Taking 8x as long is a LOT of time.

**Comment by 5731la** [comment]
It's not the XZ -9, it's mostly the capital J to lower case j, I'll show some quick results in a second

**Comment by mrcbax** [comment]
Ok im not familiar with lower j do you know the difference? Be back in a bit. I've got some other work to do.

**Comment by 007** [comment]
Lower `j` is bzip2 compression, pretty good stuff but not xz quality. I'll do a side-by-side-by-side comparison of several options for compression-vs-CPU on this kind of data tonight.

**Comment by 5731la** [comment]
heres some basic data: 
```
tar -cvjf test.tar.bz2 ./working_dir  1.68s user 0.13s system 107% cpu 1.681 total 2.1M
tar -cvJf test.tar.bz2 ./working_dir  8.44s user 0.21s system 103% cpu 8.398 total 1.9M
XZ_OPT=-9 tar -cvJf test.tar.bz2 ./working_dir  8.96s user 0.31s system 102% cpu 9.012 total 1.9M
```
using time on a ramdisk (!!!)
also its 5% not 10%
Goodnight!

**Review by mrcbax — APPROVED** [review]
It could be better somehow I can feel it but I'll go ahead and merge this.

**Pull request merged**
