### PR TITLE
Syntax cleanup and random target selection.

### PR DESCRIPTION
**Pull request by morrowc**
See commit message, but the result of the usage of 'sort -R' is:

$ grep -v '^#'  servers.txt  | grep -v '^$' | /usr/bin/sort -R | head -5
194.85.40.38
195.239.3.113
195.239.6.8
84.201.133.122
84.242.47.247

$ grep -v '^#'  servers.txt  | grep -v '^$' | /usr/bin/sort -R | head -5
91.204.129.117
193.203.102.97
195.16.54.49
195.62.52.8
212.57.113.89

$ grep -v '^#'  servers.txt  | grep -v '^$' | /usr/bin/sort -R | head -5
194.85.119.68
80.76.244.241
85.192.165.87
37.29.116.243
77.41.147.144

$ grep -v '^#'  servers.txt  | grep -v '^$' | /usr/bin/sort -R | head -5
37.29.107.1
84.253.119.85
79.134.214.149
176.32.33.159
80.66.157.253

### CODE REVIEW

**Comment by morrowc** [comment]
As an aside, and in another PR I'll try to do this, you SHOULD not make a single directory with >1k files, on many filesystems that is: "going to end poorly" from a performance perspective anyway.

So, you'd want to drop the probe result files (in ${working_dir}) in some hash-based named directory structure.. and the tarballs should also end in the same sort of path in the storage location. I'll take a shot at something for this in a bit.

**Comment by Colseph** [comment]
theres an [issue](https://github.com/LogoiLab/frwl/issues/4) open where we've talked about similar stuff if your interested. (nice syntax btw, clean code is best code ;P)

**Comment by morrowc** [comment]
were we talked about which " the filesystem disaster or the random selection? :) (reading issue)

**Comment by 5731la** [comment]
I see one issue here which is that, by default, thers 5k servers in servers.txt which would crash any realistic server. I like my approach (in my personal program that hasnt been PR'd yet) to have a serverstouse.txt file. Ill edit this in the PR momentarily

**Comment by Colseph** [comment]
@morrowc random selection.

**Comment by 5731la** [comment]
Oh, thats probably a better solution actually.

**Comment by mrcbax** [comment]
Ok so I merged the newer PR that i think you said contained this so one of us can go ahead and close this is what I'm assuming?

**Comment by morrowc** [comment]
fixed up branch merge issues.

**Review by mrcbax — APPROVED** [review]

**Pull request merged**
