### PR TITLE
removing --remove-files from tar for freeBSD folks

### PR DESCRIPTION
**Pull request by 5731la**
prevents the following error:
```
traceroute to 178.238.121.241 (178.238.121.241), 64 hops max, 48 byte packets
tar: --remove-files: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
```

### CODE REVIEW

**Comment by mrcbax** [comment]
I'm sorry but that will cause the working directory to fill extremely quickly, it's not storage efficient.

**Comment by 5731la** [comment]
Ok, but out of curiosity, what does it do and can I find a way to do it manually?

**Comment by Colseph** [comment]
it just deletes the files after theyve been added to the tarball.
you _could_ just swap it for an `rm`
something like:
`XZ_OPT=-9 tar cJf "$TARBALL_DIR/$COMP_ITER.$TIME.$SERVER.tar.xz" "$WORKING_DIR"/*; rm "$WORKING_DIR"/*`
but _**if**_ the tar fails for some reason it'll still the files and you could be out hour(s) of data

**Comment by 5731la** [comment]
could we just check error codes?

**Comment by Colseph** [comment]
yeah `[ "$?" == "0" ] &&` before the `rm` should probably work

**Comment by 5731la** [comment]
I'll write it when I can sit down and do it, unless you'd rather do it.

**Comment by 007** [comment]
`tar... && rm...` instead of checking codes, let the shell do it for you.

**Comment by 5731la** [comment]
see newest commit, implementing the strategy mentioned by @007

**Comment by Colseph** [comment]
lol totally missed that thnx Ryan

**Comment by mrcbax** [comment]
There have been a couple of cleanliness changes to the code that are causing some merge conflicts I'm going to suggest the person who created this request to go ahead and do a git pull, resolve the conflicts then push the changes back over the request.

**Comment by 5731la** [comment]
I'll check it out in a few

**Comment by 5731la** [comment]
Hey, I dont have perms to resolve conflicts apparently since I dont have the perms to merge it (no write access)..? https://imagen.click/i/83d0c6.png

**Comment by 5731la** [comment]
no merge errors now..?

**Comment by 5731la** [comment]
dammit more merge errors, Ill need to fix this when I get home, but can we just push this sooner rather than later?

**Comment by 5731la** [comment]
well now it lets me do it in github.... so its ready I guess @LogoiLab

**Pull request merged**
