### PR TITLE
updated because we dont use hashes.txt anymore

### PR DESCRIPTION
**Pull request by 5731la**

### CODE REVIEW

**Comment by mrcbax** [comment]
We will be. I'm going to be copying survey responses into it. And writing a script to sequentially pull data off the network using it.

**Comment by mrcbax** [comment]
That way it all stays public too

**Comment by 5731la** [comment]
Ok but do we want people adding stuff to it directly?

**Comment by mrcbax** [comment]
They have it as an option if they want.

**Pull request closed without merging**
