### PR TITLE
RE-create the directories upon tar creation

### PR DESCRIPTION
**Pull request by morrowc**
Fixed line64 error and line 95 error, and reduced directory splay to 2 levels.

### CODE REVIEW

**Comment by mrcbax** [comment]
Had to revert that commit there's an error in your `head` syntax

**Comment by mrcbax** [comment]
`head: invalid option -- '.'`

**Comment by mrcbax** [comment]
any reason for the change to baz2?

**Comment by morrowc** [comment]
I think head will fail if there's no 'PROBES' set.. so I set a default 1 for that.
Also.. I expect the rm ${WORKING_DIR} inside tarball is going to fail:

	tar cjf "${TARBALL_DIR}/${_randomDir}/${COMP_ITER}.${TIME}.${SERVER}.tar.bz2" "${WORKING_DIR}"/* && rm "$WORKING_DIR"/*

should be -rf there...added that.

baz2? you mean: bz2 ? (tar -J is 'bzip2 format compression')

**Comment by mrcbax** [comment]
yea you can blame @gidoBOSSftw5731 on that rm stuff. freebsd compatibility. and cool.

**Comment by mrcbax** [comment]
let me know when you feel its ready to merge

**Comment by morrowc** [comment]
anyway.. I think that should work for you now.

**Comment by mrcbax** [comment]
I'm considering giving some contributors push access to the repo.

**Comment by morrowc** [comment]
argh, wait

**Comment by mrcbax** [comment]
I can wait

**Comment by morrowc** [comment]
ok that's currently running ok, I think, in my fork.

**Comment by morrowc** [comment]
argh. Bits and pieces got reverted in my fork. wait again.

**Comment by morrowc** [comment]
ok, doesn't error for realz this time.

**Comment by mrcbax** [comment]
alright ready to merge?

**Comment by morrowc** [comment]
yes.

**Review by mrcbax — APPROVED** [review]

**Pull request merged**
